#!/usr/bin/perl

use constant {
    VERSION => "gencc v0.1\n",
    USAGE   => "usage: $0 [-n COUNT] [--] CARDS...\n",
};

use strict;
use warnings;
use feature 'say';

use Getopt::Std;
use POSIX;

my %cards = (
    VISA        =>  {
        prefix  =>  [qw( 4539 4556 4916 4532 4929 40240071 4485 4716 4 )],
    },

    MASTERCARD  =>  {
        prefix  =>  [qw( 51 52 53 54 55
                         2221 2222 2223 2224 2225 2226 2227 2228 2229
                         223 224 225 226 227 228 229
                         23 24 25 26
                         270 271 2720 )],
        digits  =>  16,
    },

    AMEX        =>  {
        prefix  =>  [qw( 34 37 )],
        digits  =>  15,
    },

    DISCOVER    =>  {
        prefix  =>  [qw( 6011 )],
        digits  =>  16,
    },

    DINERS      =>  {
        prefix  =>  [qw( 300 301 302 303 36 38 )],
        digits  =>  14,
    },

    ENROUTE     =>  {
        prefix  =>  [qw( 2014 2149 )],
        digits  =>  15,
    },

    JCB         =>  {
        prefix  =>  [qw( 35 )],
        digits  =>  16,
    },

    VOYAGER     =>  {
        prefix  =>  [qw( 8699 )],
        digits  =>  15,
    },
);

$cards{ VISA13 }{prefix} = \$cards{ VISA }{prefix}->@*;
$cards{ VISA13 }{digits} = 13;
$cards{ VISA16 }{prefix} = \$cards{ VISA }{prefix}->@*;
$cards{ VISA16 }{digits} = 16;

# Generate CC number:
# 'prefix' is the start of the CC number as a string, any number digits.
# 'length' is the length of the CC number to generate. Typically 13 or 16.
sub completed_number {
    my ($prefix, $length) = @_;

    my $ccnumber = $prefix;

    # generate digits
    $ccnumber .= int(rand 10) while length $ccnumber < $length - 1;

    # calculate sum
    # Luhn Algorithm http://en.wikipedia.org/wiki/Luhn_algorithm
    my $sum = 0;
    my $pos = 0;
    my $reversed_ccnumber = scalar reverse $ccnumber;

    while ($pos < $length - 1) {
        my $odd = substr($reversed_ccnumber, $pos, 1) * 2;
        $odd -= 9 if $odd > 9;

        $sum += $odd;
        $sum += substr($reversed_ccnumber, $pos+1, 1) if $pos != $length - 2;

        $pos += 2;
    }

    # calculate check digit
    my $check_digit = ((floor($sum / 10) + 1) * 10 - $sum) % 10;
    $ccnumber .= $check_digit;

    return $ccnumber;
}

# TODO
sub credit_card_number {
    my ($card, $length, $how_many) = @_;
    my @result;

    for my $i (0 .. $how_many - 1) {
        my $prefixes = scalar $cards{ $card }{prefix}->@*;
        my $choice   = rand $prefixes;

        my $ccprefix = $cards{ $card }{prefix}[ $choice ];

        push @result, completed_number( $ccprefix, $length );
    }

    return \@result;
}

###############################################################################

use vars qw($opt_h $opt_n $opt_v);
getopts('hn:v');

print USAGE   and exit if $opt_h;
print VERSION and exit if $opt_v;

@ARGV = keys %cards if @ARGV == 1 && uc $ARGV[0] eq 'ALL';

for my $arg (@ARGV) {
    my $card = uc $arg;
    next if not exists $cards{ $card } or $card eq 'VISA';

    my $digits = $cards{ $card }{digits};

    say "# $card";
    say for credit_card_number($card, $digits, $opt_n || 1)->@*;
}

# vim:sw=4:ts=4:sts=4:et:cc=80
# End of file
